name: Test print files new structure
# Workflow runs when manually triggered using the  UI or API.

# Job Inputs: These options are selected before the workflow run starts
on:
  workflow_dispatch:
    inputs:
      # The branch that is going to be used for the tests
      branch:
        description: 'Branch to checkout from'
        required: false
        default: 'feature/IOSMNS-13627/iOS-pipeline-based-on-new-folder-structure'
      # Desired platform to run the tests
      platform:
        description: 'Platform to run tests'
        required: true
        type: choice
        options:
          - iOS
          - Android
      build_slug:
        description: 'Bitrise build slug'
        required: false
        default: ''
      update_zephyr:
        description: 'Upload test results to zephyr'
        required: true
        type: boolean
        default: false

jobs:
  debug_workflow:
    name: Debug workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print input parameters
        run: |
          echo "github.event.inputs.branch: ${{ github.event.inputs.branch }}"
          echo "github.event.inputs.platform: ${{ github.event.inputs.platform }}"
          echo "github.event.inputs.build_slug: ${{ github.event.inputs.build_slug }}"
          echo "github.event.inputs.update_zephyr: ${{ github.event.inputs.update_zephyr }}"

  checkOut_action:
    name: Checkout action
    runs-on: ubuntu-latest
    needs: debug_workflow
    steps:
      - name: Checkout from ${{ github.event.inputs.branch }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

  call_team_regression_test_example:
    name: Call regression test example by team
    needs: checkOut_action
    #strategy:
    #  matrix:
    #    team: [ firestarters, autobots ]
    #uses: ./.github/workflows/appium-regression-new-structure.yml
    uses: aleaguirre96/workflow-example-yml/.github/workflows/appium-regression-new-structure.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      platform: ${{ github.event.inputs.platform }}
      build_slug: ${{ github.event.inputs.build_slug }}
      update_zephyr: ${{ github.event.inputs.update_zephyr }}
      team: firestarters

  #last_job_verification:
  #  name: List a message to know that all job finish
  #  runs-on: ubuntu-latest
  #  needs: call_team_regression_test_example
  #  steps:
  #    - name:
  #      run: |
  #        echo "All jobs ran."
